[window]

padding.x = 10
padding.y = 10

decorations_theme_variant = "Dark"

[font]

size = 12.0

[general]

import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

[terminal.shell]
program = "/bin/zsh"
