[window]

padding.x = 10
padding.y = 10

decorations_theme_variant = "Dark"

[font]

size = 11.5
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[general]

import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[terminal.shell]
program = "/bin/zsh"
